export const optionsGroups = [
  {
    groupName: 'A',
    options: [
      { name: 'Alabama', icon: 'mic', isSelected: true },
      { name: 'Alaska', icon: 'mic', isSelected: true },
      { name: 'Arizona', icon: 'mic', isSelected: true },
      { name: 'Arkansas', icon: 'mic', isSelected: true },
    ],
    isSelected: true,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'C',
    options: [
      { name: 'California', icon: 'mic', isSelected: false },
      { name: 'Colorado', icon: 'mic', isSelected: false },
      { name: 'Connecticut', icon: 'mic', isSelected: false },
    ],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'D',
    options: [{ name: 'Delaware', icon: 'mic', isSelected: false }],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'F',
    options: [{ name: 'Florida', icon: 'mic', isSelected: false }],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'G',
    options: [{ name: 'Georgia', icon: 'mic', isSelected: false }],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'H',
    options: [{ name: 'Hawaii', icon: 'mic', isSelected: false }],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'I',
    options: [
      { name: 'Idaho', icon: 'mic', isSelected: false },
      { name: 'Illinois', icon: 'mic', isSelected: false },
      { name: 'Indiana', icon: 'mic', isSelected: false },
      { name: 'Iowa', icon: 'mic', isSelected: false },
    ],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'K',
    options: [
      { name: 'Kansas', icon: 'mic', isSelected: false },
      { name: 'Kentucky', icon: 'mic', isSelected: false },
    ],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'L',
    options: [{ name: 'Louisiana', icon: 'mic', isSelected: false }],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'M',
    options: [
      { name: 'Maine', icon: 'mic', isSelected: false },
      { name: 'Maryland', icon: 'mic', isSelected: false },
      { name: 'Massachusetts', icon: 'mic', isSelected: false },
      { name: 'Michigan', icon: 'mic', isSelected: false },
      { name: 'Minnesota', icon: 'mic', isSelected: false },
      { name: 'Mississippi', icon: 'mic', isSelected: false },
      { name: 'Missouri', icon: 'mic', isSelected: false },
      { name: 'Montana', icon: 'mic', isSelected: false },
    ],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'N',
    options: [
      { name: 'Nebraska', icon: 'mic', isSelected: false },
      { name: 'Nevada', icon: 'mic', isSelected: false },
      { name: 'New Hampshire', icon: 'mic', isSelected: false },
      { name: 'New Jersey', icon: 'mic', isSelected: false },
      { name: 'New Mexico', icon: 'mic', isSelected: false },
      { name: 'New York', icon: 'mic', isSelected: false },
      { name: 'North Carolina', icon: 'mic', isSelected: false },
      { name: 'North Dakota', icon: 'mic', isSelected: false },
    ],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'O',
    options: [
      { name: 'Ohio', icon: 'mic', isSelected: false },
      { name: 'Oklahoma', icon: 'mic', isSelected: false },
      { name: 'Oregon', icon: 'mic', isSelected: false },
    ],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'P',
    options: [{ name: 'Pennsylvania', icon: 'mic', isSelected: false }],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'R',
    options: [{ name: 'Rhode Island', icon: 'mic', isSelected: false }],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'S',
    options: [
      { name: 'South Carolina', icon: 'mic', isSelected: false },
      { name: 'South Dakota', icon: 'mic', isSelected: false },
    ],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'T',
    options: [
      { name: 'Tennessee', icon: 'mic', isSelected: false },
      { name: 'Texas', icon: 'mic', isSelected: false },
    ],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'U',
    options: [{ name: 'Utah', icon: 'mic', isSelected: false }],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'V',
    options: [
      { name: 'Vermont', icon: 'mic', isSelected: false },
      { name: 'Virginia', icon: 'mic', isSelected: false },
    ],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
  {
    groupName: 'W',
    options: [
      { name: 'Washington', icon: 'mic', isSelected: false },
      { name: 'West Virginia', icon: 'mic', isSelected: false },
      { name: 'Wisconsin', icon: 'mic', isSelected: false },
      { name: 'Wyoming', icon: 'mic', isSelected: false },
    ],
    isSelected: false,
    isOpened: true,
    icon: 'flight',
  },
];
